### ISSUE TITLE
Missing weight sharing?

### ISSUE THREAD

**Issue by jiayiliu** [InnerPeace-Wu/CapsNet-tensorflow#1]
Hi
Thank you for sharing your implementation.  It is quite helpful!

However, I think you missed the weight sharing part (see page 4, under figure 2, each capsule in [6,6] grid is sharing their weights).  So my understanding is that your `cap_ws` should have the last dim of 32, instead of 1152.

Although I tested both cases, in the early training stage, I didn't see too much difference.

**Comment by InnerPeace-Wu** [comment]
Hi,
![image](https://user-images.githubusercontent.com/22615736/32412985-5feb5268-c1cc-11e7-9057-f0a82251a795.png)
I think it means that each capsule in the [6,6] grid **shares the weights of conv op** which have the shape `8 x 9x9 x 256` for each of 32 channels of the `PrimaryCaps`(i.e. sharing feature detector spatially), and it's not about sharing weights with `DigitCaps`.

**Comment by jiayiliu** [comment]
Thanks.  I thought the same way at the beginning.  

Never mind.  In this way, we actually treat the 6*6*32 capsules as individual ones. I am just not sure whether they have a specific reason to put a 32-layer representation here.

**Comment by InnerPeace-Wu** [comment]
Glad that we share the same idea.
As for the choice of 32-channels of PrimaryCaps, I suppose it's kind of similar to the output channel in traditional conv nets, where we usually select 256, 512 etc. In this case, we choose 8x32=256 as the output channel, since the capsule needs to be a vector and we choose 8 as number of units in one vector, so finally, the channel of Primary caps would be 32. In a word, i think there is no specific reason, but following conventional instinct building a network with conv ops.
best,
